### ISSUE TITLE
jsonDecoder issue

### ISSUE THREAD

**Issue by danielhemmati** [Jayapraveen/INE-courses-downloader#1]
i just wanted to download courses from INE, and here is the error i got. 

do you have any idea?

thanks for your time 😀

```bash
Logged in to INE as Corporate User with XXXXX@XXXXX.com

Choose Method Of Operation:
1.Site Rip
2.Select Individual Course
1
Traceback (most recent call last):
  File "c:/Users/Daniel/Desktop/ine/INE-courses-downloader/Ine.py", line 277, in <module>
    all_courses = total_courses()
  File "c:/Users/Daniel/Desktop/ine/INE-courses-downloader/Ine.py", line 182, in total_courses
    all_courses = json.loads(course_handler.readline())
  File "c:\users\daniel\appdata\local\programs\python\python38\Lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "c:\users\daniel\appdata\local\programs\python\python38\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\users\daniel\appdata\local\programs\python\python38\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by Jayapraveen** [comment]
Hello @danielhemmati 
The issue has been fixed with the latest release. Please ensure you have write access to the folder where the script is present and try to rerun the latest script after deleting the "ine_courses.txt" file if present in the folder where your script is located and thankyou for reporting the issue. 😀
