### ISSUE TITLE
You do not have the subscription/pass to access to this course error

### ISSUE THREAD

**Issue by brattip** [Jayapraveen/INE-courses-downloader#16]
Hi,
I'm try to use your app, otherwise the system doesn't recognize my monthly pass ... can u check it?
from web site it works fine
let me know

```
Choose Preferred Video Quality
1.Highest Available Quality (1080p)
2.Next To Highest Quality (720p)
2
Choose Method Of Selecting Course
1.Enter url
2.Choose from the above listed course
3.Download a select number of courses from the above list
4.Download a bunch of courses from the above list using a range
2
Please enter the number corresponding to the course you would like to download
821
You do not have the subscription/pass to access to this course
root@ubuntu:~# 
```

**Comment by telus-beep** [comment]
I am having same error.

**Comment by telus-beep** [comment]
Will someone fix this issue before my subscription expires ??

**Comment by vikdean** [comment]
Same thing here, whatever I enter, it doesn't work.

**Comment by telus-beep** [comment]
not sure when will he look into this and fix it, the case was opened 15 days ago but no action taken by the Code Developer so far :(

**Comment by vikdean** [comment]
If you take out the subscription check, it works:
```
        elif(choice == 2):
            choice = int(input("Please enter the number corresponding to the course you would like to download\n"))
            course = all_courses[choice]
            #if(course["access"]["related_passes"][pass_index_value]["name"] in access_pass):
            downloader(course)
            #else:
            #    exit("You do not have the subscription/pass to access to this course")
```

You can do the same for the other options. I know its not optimal, but still...

**Comment by telus-beep** [comment]
no it does not work, I don't see that subscription error anymore. It takes the option and exits out.

Choose Preferred Video Quality
1.Highest Available Quality (1080p)
2.Next To Highest Quality (720p)
2
Choose Method Of Selecting Course
1.Enter url
2.Choose from the above listed course
3.Download a select number of courses from the above list
4.Download a bunch of courses from the above list using a range
2
Please enter the number corresponding to the course you would like to download
10

C:\Users\t940908\Desktop\INE-courses-downloader>

**Comment by vikdean** [comment]
Not sure it isn't working for you, but beside adding a Python shebang to the first line, I commented out those lines and modified the indentation for the `downloader(course)` line; that's it. Haven't done anything else.

**Comment by telus-beep** [comment]
My bad, I overlooked your edited lines and didn't notice the indentation. I am not a python or scripting guy.

But it works now, thanks a lot 👍

**Comment by akanii** [comment]
Hello I get that error when i run the script,  SyntaxError: invalid syntax
python Ine.py                                                            2 ⨯
  File "Ine.py", line 444
    p.map(downloader,(all_courses[j] for j in range(i, this_session) if (False if (len(all_courses[j]["access"]["related_passes"]) == 0) else True if (course_has_access(all_courses[j])) else False) and 1 or print("Course not in subscription access pack. Skipping ..")))

**Comment by akanii** [comment]
@vikdean I have same issue after i selected the course just that message will appear, any solution thanks.

Choose Preferred Video Quality
1.Highest Available Quality (1080p)
2.Next To Highest Quality (720p)
1
Choose Method Of Selecting Course
1.Enter url
2.Choose from the above listed course
3.Download a select number of courses from the above list
4.Download a bunch of courses from the above list using a range
2
Please enter the number corresponding to the course you would like to download
3
You do not have the subscription/pass to access to this course

**Comment by akanii** [comment]
> Not sure why it isn't working for you, but beside adding a Python shebang to the first line, I commented out those lines and modified the indentation for the `downloader(course)` line; that's it. Haven't done anything else.

Thanks also

**Comment by telus-beep** [comment]
Now I get this new error

Choose Preferred Video Quality
1.Highest Available Quality (1080p)
2.Next To Highest Quality (720p)
1
Choose Method Of Selecting Course
1.Enter url
2.Choose from the above listed course
3.Download a select number of courses from the above list
4.Download a bunch of courses from the above list using a range
4
Enter the starting course number(Inclusive)
0
Enter the closing course number(Inclusive)
843
Server doesn't support HEAD.

**Comment by akanii** [comment]
just fellow @vikdean steps

**Comment by telus-beep** [comment]
Hi @vikdean ( any fix for this error ) ??

Downloading: CiscoNetworkAccessSecurity: 0%| | 0.00/1.00 [00:00<?, ?course/s]
Traceback (most recent call last):
File "c:/Users/boy/INE-courses-downloader/Ine.py", line 479, in
downloader(course)
File "c:/Users/boy/INE-courses-downloader/Ine.py", line 352, in downloader
os.makedirs(subfolder_name)
File "C:\Users\boy\AppData\Local\Programs\Python\Python36-32\lib\os.py", line 220, in makedirs
mkdir(name, mode)
NotADirectoryError: [WinError 267] The directory name is invalid: '1.Access Control : Network'

I think the problem is '1. Access Control : Network' ( : ) that character not allowed as name of the folder.

**Comment by telus-beep** [comment]
@dexter101010 any help will appreciated..
