### ISSUE TITLE
Error when attempting to download any course

### ISSUE THREAD

**Issue by FrostMatt** [Jayapraveen/INE-courses-downloader#18]
Error message displayed when trying to download any course. Using latest version of Ine.py as of 22/03/2021.
Thanks.

```
Total 836 courses

Choose Preferred Video Quality
1.Highest Available Quality (1080p)
2.Next To Highest Quality (720p)
1
Choose Method Of Selecting Course
1.Enter url
2.Choose from the above listed course
3.Download a select number of courses from the above list
4.Download a bunch of courses from the above list using a range
2
Please enter the number corresponding to the course you would like to download
69
Traceback (most recent call last):
  File "Ine.py", line 478, in <module>
    if(course_has_access(course)):
  File "Ine.py", line 128, in course_has_access
    return boolean
UnboundLocalError: local variable 'boolean' referenced before assignment
```

**Comment by telus-beep** [comment]
You have to edit this section of the script. Comment out the lines

elif(choice == 2):
            choice = int(input("Please enter the number corresponding to the course you would like to download\n"))
            course = all_courses[choice]
            #if(course_has_access(course)):
            downloader(course)
            #else:
            #    exit("You do not have the subscription/pass to access to this course")
