### ISSUE TITLE
You do not have the subscription/pass to access to this course

### ISSUE THREAD

**Issue by telus-beep** [Jayapraveen/INE-courses-downloader#26]
I have full site access to the INE courses, but this script keeps saying no subscription. No matter what option I try.

Choose Preferred Video Quality
1.Highest Available Quality (1080p)
2.Next To Highest Quality (720p)
1
Choose Method Of Selecting Course
1.Enter url
2.Choose from the above listed course
3.Download a select number of courses from the above list
4.Download a bunch of courses from the above list using a range
4
Enter the starting course number(Inclusive)
0
Enter the closing course number(Inclusive)
863
You do not have the subscription/pass to access to this course
You do not have the subscription/pass to access to this course
You do not have the subscription/pass to access to this course
You do not have the subscription/pass to access to this course
You do not have the subscription/pass to access to this course
You do not have the subscription/pass to access to this course
You do not have the subscription/pass to access to this course
You do not have the subscription/pass to access to this course
You do not have the subscription/pass to access to this course
You do not have the subscription/pass to access to this course
You do not have the subscription/pass to access to this course
You do not have the subscription/pass to access to this course
You do not have the subscription/pass to access to this course
You do not have the subscription/pass to access to this course
You do not have the subscription/pass to access to this course
You do not have the subscription/pass to access to this course
You do not have the subscription/pass to access to this course
You do not have the subscription/pass to access to this course
You do not have the subscription/pass to access to this course
Traceback (most recent call last):
  File "Ine.py", line 714, in <module>
    if(course_has_access(course)):
  File "Ine.py", line 151, in course_has_access
    return boolean
UnboundLocalError: local variable 'boolean' referenced before assignment

=============================================================================

863. CCIE R&S Advanced Technologies Class Version 4.5
Total 864 courses

Choose Preferred Video Quality
1.Highest Available Quality (1080p)
2.Next To Highest Quality (720p)
1
Warning! This is a high compute and throughput functionality and needs
lots and lots of compute time and storage space 
Enter "I agree" to acknowledge and proceed!
I agree

Initializing for Site dump

  0%|                                                                                                                                                                                        | 0/1 [00:00<?, ?it/s]
Courses to be downloaded this batch: 0  to  1
Course not in subscription access pack. Skipping ..

Course batch successfully completed downloading.. Starting Next batch..

Courses to be downloaded this batch: 1  to  2                                                                                                                                                | 0/1 [00:00<?, ?it/s]
Course not in subscription access pack. Skipping ..

Course batch successfully completed downloading.. Starting Next batch..

Courses to be downloaded this batch: 2  to  3
Course not in subscription access pack. Skipping ..                                                                                                                                          | 0/1 [00:00<?, ?it/s]

Course batch successfully completed downloading.. Starting Next batch..

Courses to be downloaded this batch: 3  to  4
Course not in subscription access pack. Skipping ..
  0%|                                                                                                                                                                                        | 0/1 [00:00<?, ?it/s]
Course batch successfully completed downloading.. Starting Next batch..

Courses to be downloaded this batch: 4  to  5
Course not in subscription access pack. Skipping ..

**Comment by K4leds** [comment]
were you able to find a fix? having the same issue.
