### ISSUE TITLE
“Temporary failure in name resolution”

### ISSUE THREAD

**Issue by Hamzahxxvii** [Jayapraveen/INE-courses-downloader#29]
Im always getting this kind of error when downloading a course, ive tried 3 times and the download progress was never completed. Anyone who got an idea, please help!!!

**Comment by Hamzahxxvii** [comment]
Choose Preferred Video Quality
1.Highest Available Quality (1080p)
2.Next To Highest Quality (720p)
2
Free Subscription Detected! Do not enter courses not accessible with your account...

Choose Method Of Selecting Course
1.Enter url
2.Choose from the above listed course
3.Download a select number of courses from the above list
4.Download a bunch of courses from the above list using a range
2
Please enter the number corresponding to the course you would like to download
121
Downloading course file: INE Cyber Security Pass - User Guide.pdf: 100%|█| 1.00/1.00 [00:02<00:00, 2.39s/fi
Downloading: Penetration Testing Prerequisites:   0%|                      | 0.00/1.00 [00:00<?, ?course/sVideo already downloaded.. skipping Downloading..|██████▊         | 3.00/7.00 [00:12<00:15, 3.92s/videofile]
                                                                                                          Video already downloaded.. skipping Downloading..first-lab-001-v2-hd.mp4:  71%|▋| 5.00/7.00 [00:15<00:06, 3.

Downloading: 2.VOD-4194_lab0_connecting-to-your-first-lab-001-v2-hd.mp4: 100%|█| 7.00/7.00 [00:24<00:00, 3.      
                                                                                                          ^ 67%|████████████████████████████████████████                    | 8.00/12.0 [08:53<04:26, 66.7s/videofile]
Downloading: Penetration Testing Prerequisites:   0%|                      | 0.00/1.00 [09:18<?, ?course/s]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1012, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f3d289fc340>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='els-cdn.content-api.ine.com', port=443): Max retries exceeded with url: /c5e74349-0e22-4c9f-8a2e-9c122a7bb05e/data/slide35.js (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3d289fc340>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/INE-courses-downloader/Ine.py", line 682, in <module>
    downloader(course)
  File "/home/kali/INE-courses-downloader/Ine.py", line 557, in downloader
    download_slides(k["uuid"], slide_index)
  File "/home/kali/INE-courses-downloader/Ine.py", line 392, in download_slides
    out = requests.get(slidejs_url.format(uuid,str(num)), headers=header, cookies=cookies)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='els-cdn.content-api.ine.com', port=443): Max retries exceeded with url: /c5e74349-0e22-4c9f-8a2e-9c122a7bb05e/data/slide35.js (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3d289fc340>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
