### ISSUE TITLE
KeyError: 'Refresh' Refresh token is not returned 

### ISSUE THREAD

**Issue by Ahm3dRN** [Jayapraveen/INE-courses-downloader#49]
I'm trying to use the script but I'm getting an Error: "KeyError: 'Refresh'" 
printing login_data produces this which doesn't seem to have a Refresh field
private info hidden
```
Enter your Password:

{'data': {'id': '', 'username': '', 'customer_id': , 'email': '', 'origin': 'checkout.ine.com', 'links': {'rel': 'self', 'uri': '/users/'}, 'team_ids': [], 'suspended': False, 'account_id': '', 'mfa_required': False, 'mfa_method': None, 'subscriber_status': 'active', 'starter_opt_in_at': None, 'created_at': '2022-09-11', 'confirmed_at': '2022-09-11 ', 'is_confirmed': True, 'tokens':
 {'data': {'Bearer': ''}}, 'roles': {'data': [{'id': '', 'name': 'Customer', 'is_primary': 1}]}, 'profile': {'data': {'first_name': '', 'last_name': '', 'avatar': '', 'preferred_phone_number': None}}}}
Traceback (most recent call last):
  File "Ine.py", line 616, in <module>
    login()
  File "Ine.py", line 76, in login
    refresh_token = login_data["data"]["tokens"]["data"]["Refresh"]
KeyError: 'Refresh'

```

**Comment by Ahm3dRN** [comment]
I did as suggested here  seems to be okay
https://github.com/Jayapraveen/INE-courses-downloader/issues/34#issuecomment-1114037956
