### ISSUE TITLE
Some courses cannot be downloaded 

### ISSUE THREAD

**Issue by dexter101010** [Jayapraveen/INE-courses-downloader#5]
Hi bro , 

It seems that some courses cannot be downloaded. When i try to download a course it give me this error : 

Please enter the number corresponding to the course you would like to download
63
Downloading course file: INE Cyber Security Pass - User Guide.pdf: 100%|███████████████████████████████████████████████████████████| 1/1 [00:05<00:00,  5.48s/it]
Downloading: MalwareAnalysis:   0%|                                                                                                        | 0/1 [00:00<?, ?it/s]
  0%|                                                                                                                                      | 0/6 [00:00<?, ?it/s]Preferred video not available.
Inferior quality video is only available and it is chosen..

 17%|█████████████████████                                                                                                         | 1/6 [00:01<00:07,  1.45s/it]
Downloading: MalwareAnalysis:   0%|                                                                                                        | 0/1 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "Ine.py", line 461, in <module>
    downloader(course)
  File "Ine.py", line 344, in downloader
    download_video(out[1],out[0])
  File "Ine.py", line 261, in download_video
    video = requests.get(url, stream=True)
  File "C:\Program Files\Python36\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\requests\sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "C:\Program Files\Python36\lib\site-packages\requests\sessions.py", line 459, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Program Files\Python36\lib\site-packages\requests\models.py", line 314, in prepare
    self.prepare_url(url, params)
  File "C:\Program Files\Python36\lib\site-packages\requests\models.py", line 388, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '0': No schema supplied. Perhaps you meant http://0?

Regards :)

**Comment by CoolRoot** [comment]
Having the same issue as well

**Comment by Jayapraveen** [comment]
Fixed in commit `695d349`.
