### ISSUE TITLE
NameError: name 'access_token' is not defined

### ISSUE THREAD

**Issue by HamzaNakabi** [Jayapraveen/INE-courses-downloader#50]
Every time I test the script I have this error : 
Traceback (most recent call last):
  File "C:\Users\Lenovo\Downloads\INE-courses-downloader-master\Ine.py", line 617, in <module>
    access_pass = pass_validator()
  File "C:\Users\Lenovo\Downloads\INE-courses-downloader-master\Ine.py", line 187, in pass_validator
    header = {"Host": host,"Origin": referer,"Authorization": access_token,"User-Agent": user_agent,"Accept": accept,"X-Requested-With": x_requested_with,"Accept-Encoding": accept_encodings,"sec-fetch-mode": sec_fetch_mode,"sec-fetch-dest": sec_fetch_dest,"Referer": referer}
NameError: name 'access_token' is not defined

**Comment by Jamsgrove** [comment]
I also have this issue, fresh install and running 20.04.5 LTS with Python 3.8.10

**Comment by Master-Chief07** [comment]
Getting the same error

**Comment by syedsoftdev** [comment]
i have also same error
